[workspace]
resolver = "2"

members = ["day*"]


[workspace.dependencies]
# vector/matrix library
glam = "0.24.2"
# iteration helpers
itertools = "0.12.0"
# parsing
nom = "7.1.3"
# graph library
petgraph = "0.6.4"
# parrallelism
rayon = "1.8.0"
# inline string literals
indoc = "2.0.4"
